FROM debian:11

RUN apt update && apt upgrade -y

RUN apt install mariadb-server -y

COPY ./conf/conf.cnf /etc/mysql/mariadb.conf.d/50-server.cnf

COPY ./conf/script.sh ./script.sh

RUN chmod +x ./script.sh

CMD ["./script.sh"]