FROM debian:11

RUN apt-get update -y
RUN apt-get install nginx -y
RUN apt-get install -y openssl
RUN mkdir -p /etc/nginx/ssl

COPY ./conf/nginx.conf  /etc/nginx/nginx.conf
COPY ./conf/script.sh /

RUN chmod +x /script.sh

CMD ["./script.sh"]